#!/bin/sh

#
#    00-custom-header - custom MOTD header shown in login
#    Authors: Agastyo Satriaji Idam <play.satriajidam@gmail.com>
#

upSeconds="$(/usr/bin/cut -d. -f1 /proc/uptime)"
secs=$((${upSeconds}%60))
mins=$((${upSeconds}/60%60))
hours=$((${upSeconds}/3600%24))
days=$((${upSeconds}/86400))
UPTIME=`printf "%d days, %02dh%02dm%02ds" "$days" "$hours" "$mins" "$secs"`
 
# get the load averages
read one five fifteen rest < /proc/loadavg

echo ""
echo "          _.-'~~~~~~'-._ "
echo "         /      ||      \           This system is under the supervision of a Sith Lord."
echo "        /       ||       \          Treat carefully or Lord Vader will force choke you!"
echo "       |        ||        | "
echo "       | _______||_______ |         `date +"%A, %e %B %Y, %r"`"
echo "       |/ ----- \/ ----- \|         `uname -srmo`"
echo "      /  (     )  (     )  \ "
echo "     / \  ----- () -----  / \       Uptime.............: ${UPTIME}"
echo "    /   \      /||\      /   \      Memory.............: `free -h | grep 'Mem:' | awk {'print $3'} | sed 's/.\{1\}$//'`MB (Used) / `free -h | grep 'Mem:' | awk {'print $4'} | sed 's/.\{1\}$//'`MB (Free) / `free -h | grep 'Mem:' | awk {'print $2'} | sed 's/.\{1\}$//'`MB (Total)"
echo "   /     \    /||||\    /     \     Load Averages......: ${one}, ${five}, ${fifteen} (1, 5, 15 min)"
echo "  /       \  /||||||\  /       \    Running Processes..: `ps ax | wc -l | tr -d " "`"
echo " /_        \o========o/        _\   IP Addresses.......: `ip a | grep glo | awk '{print $2}' | head -1 | cut -f1 -d/` and `wget -q -O - http://icanhazip.com/ | tail`"
echo "   '--...__|'-._  _.-'|__...--'   "
echo "           |    ''    | "
echo ""